export const REQUEST_TASKCOUNT = "REQUEST_TASKCOUNT";
export const TASK_COUNTLOADED = "TASK_COUNTLOADED";


export const REQUEST_MOBILESELECTTAB = "REQUEST_MOBILESELECTTAB";
export const ESELECTTAB_COUNTLOADED = "ESELECTTAB_COUNTLOADED";

