export const REQUEST_TASKCOUNT = "REQUEST_TASKCOUNT";
export const TASK_COUNTLOADED = "TASK_COUNTLOADED";


export const REQUEST_MOBILESELECTTAB = "REQUEST_MOBILESELECTTAB";
export const ESELECTTAB_COUNTLOADED = "ESELECTTAB_COUNTLOADED";

export const REQUEST_MOBILENAVTREE = "REQUEST_MOBILENAVTREE";
export const NAVTREE_COUNTLOADED = "ESELECTTAB_COUNTLOADED";

